baseURL = 'https://jelenaab.netlify.app/'
languageCode = 'en-us'
title = 'JELENA AB'
theme = 'PaperMod'

[params]
ShowShareButtons = true
ShareButtons = [ "linkedin", "twitter" ]
label.icon = "jelena-logga.png"


[[menu.main]]
  identifier = 'Projekt'
  name = 'Projekt'
  url = '/Projekt/'
  weight = 20

[[menu.main]]
  identifier = 'Om oss'
  name = 'Om oss'
  url = '/Om-oss/'
  weight = 30

  [[menu.main]]
  identifier = 'Tjänster'
  name = 'Tjänster'
  url = '/Tjänster/'
  weight = 40

  [[menu.main]]
  identifier = 'Kontakta oss'
  name = 'Kontakta oss'
  url = '/Kontakta-oss/'
  weight = 50